ECE297 Storage Server: server.c File Reference
server.c File Reference
This file implements the storage server.
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <string.h>
#include <assert.h>
#include <signal.h>
#include "utils.h"
#include <time.h>
#include <stdbool.h>
#include <pthread.h>
Classes
struct _ThreadInfo
Structure storing information for each thread.
Macros
#define LOGGING 0
#define MAX_LISTENQUEUELEN 20
The maximum number of queued connections.
Typedefs
typedef struct _ThreadInfo * ThreadInfo
Functions
ThreadInfo getThreadInfo (void)
Function accessing threadinfo struct.
void releaseThread (ThreadInfo me)
Function called when thread is about to finish – unless it is called, the ThreadInfo assigned to it is lost.
int handle_command (FILE *file, int sock, char *cmd, table_list *List, struct config_params params, struct set_params sparams, struct query_params qparams)
Process a command from the client.
int main (int argc, char *argv[])
Start the storage server.
Variables
ThreadInfo runtimeThreads [MAX_CONNECTIONS]
unsigned int botRT = 0
unsigned int topRT = 0
pthread_mutex_t conditionMutex = PTHREAD_MUTEX_INITIALIZER
pthread_mutex_t handle_cmd_lock = PTHREAD_MUTEX_INITIALIZER
pthread_cond_t conditionCond = PTHREAD_COND_INITIALIZER
Detailed Description
This file implements the storage server.
The storage server should be named "server" and should take a single command line argument that refers to the configuration file.
The storage server should be able to communicate with the client library functions declared in storage.h and implemented in storage.c.
Definition in file server.c.
Function Documentation
ThreadInfo getThreadInfo (void)
Function accessing threadinfo struct.
Parameters
void There're no parameter inputs Returns a pointer to the threadinfo struct
Definition at line 56 of file server.c.
References MAX_CONNECTIONS.
int handle_command (FILE * file, int sock, char * cmd, table_list * List, struct config_params params, struct set_params sparams, struct query_params qparams)
Process a command from the client.
Parameters
sock The socket connected to the client.
cmd The command received from the client.
Returns
Returns 0 on success, -1 otherwise.
Definition at line 118 of file server.c.
References ERR_AUTHENTICATION_FAILED, ERR_INVALID_PARAM, ERR_KEY_NOT_FOUND, ERR_TABLE_NOT_FOUND, ERR_UNKNOWN, logger(), config_params::pass_, query_parsing(), sendall(), set_parsing(), and config_params::username.
Referenced by main().
int main (int argc, char * argv[])
Start the storage server.
This is the main entry point for the storage server. It reads the configuration file, starts listening on a port, and proccesses commands from clients.
Definition at line 394 of file server.c.
References config_params::concurrency, handle_command(), logger(), MAX_CMD_LEN, MAX_LISTENQUEUELEN, read_config(), recvline(), config_params::server_host, and config_params::server_port.
void releaseThread (ThreadInfo me)
Function called when thread is about to finish – unless it is called, the ThreadInfo assigned to it is lost.
Parameters
Threadinfo the pointer to the threadinfo struct is passed in void There's no return
Definition at line 82 of file server.c.
References MAX_CONNECTIONS.