ECE297 Storage Server: utils.h File Reference
utils.h File Reference
This file declares various utility functions that are can be used by the storage server and client library.
#include <stdio.h>
#include "storage.h"
#include <stdbool.h>
#include <pthread.h>
Classes
struct column_struct
struct record_struct
struct table
struct table_list
struct table_params
struct for storing information about column names in tables in configuration file
struct config_params
struct for storing information about the current configuration file
struct query_params
struct for storing information about the query parameters
struct set_params
struct for storing information about the set parameters
Macros
#define MAX_CMD_LEN (1024 * 8)
The max length in bytes of a command from the client to the server.
#define LOG(x) {printf x; fflush(stdout);}
A macro to log some information.
#define DBG(x) {printf x; fflush(stdout);}
A macro to output debug information.
#define DEFAULT_CRYPT_SALT "xx"
Default two character salt used for password encryption.
Typedefs
typedef struct column_struct column_struct
typedef struct record_struct record_struct
typedef struct table table
typedef struct table_list table_list
typedef struct table_params table_params
typedef struct config_params config_params
Functions
int keymaker (const char *index)
hashing function
bool is_alpha (char str_ptr)
Function that determines whether a character is alphanumeric character or not by using ASCII values.
int sendall (const int sock, const char *buf, const size_t len)
Keep sending the contents of the buffer until complete.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int read_config (const char *config_file, struct config_params *params)
Read and load configuration parameters.
void logger (FILE *file, char *message)
Generates a log message.
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
char * query_parsing (char *unparsed_, struct query_params *qparams)
This is a function that parses the query command from client side to be used in server side.
char * set_parsing (char *unparsed_, struct set_params *sparams)
This is a function that parses the set command from client side to be used in server side.
int record_query (char *tableName, char *predicates, int max_keys, char *keys_found, table_list *list)
int insert_table (config_params params, table_list *table_ptr)
int insert_key (const char *table, const char *key, const char *value, table_list *table_ptr, config_params params, int metadata)
int create_record (int option, int i, char *key, char *value, table_list *List, config_params params, int metadata)
int delete_record (table_list *list, char *table, char *key)
int record_get (char *table, char *key, table_list *list, char *append, int *metadata)
bool find_table (char *table, table_list *table_ptr)
record_struct * find_record (char *table, char *key, table_list *list)
Variables
FILE * file_ptr
Detailed Description
This file declares various utility functions that are can be used by the storage server and client library.
Definition in file utils.h.
Macro Definition Documentation
#define DBG (x) {printf x; fflush(stdout);}
A macro to output debug information.
It is only enabled in debug builds.
Definition at line 54 of file utils.h.
#define LOG (x) {printf x; fflush(stdout);}
A macro to log some information.
Use it like this: LOG(("Hello %s", "world\n"))
Don't forget the double parentheses, or you'll get weird errors!
Definition at line 44 of file utils.h.
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns
Returns encrypted password.
Definition at line 1223 of file utils.c.
References DEFAULT_CRYPT_SALT.
Referenced by storage_auth().
bool is_alpha (char str_ptr)
Function that determines whether a character is alphanumeric character or not by using ASCII values.
Parameters
str_ptr The character that's being evaluated. If the character is alphanumeric, return true. If not, return false.
Definition at line 546 of file utils.c.
int keymaker (const char * key)
hashing function
Parameters
index The key to be inserted
Returns
Returns hashed int key
hashing function
Parameters
key String to be hashed into an integer key
Returns
Returns the integer key
Address to the record
Get a certain number from multiplication of ascii char
Makes a key from the result of both above
Definition at line 96 of file utils.c.
void logger (FILE * file, char * message)
Generates a log message.
Parameters
file The output stream
message Message to log.
Definition at line 1208 of file utils.c.
Referenced by handle_command(), and main().
char* query_parsing (char * unparsed_, struct query_params * qparams)
This is a function that parses the query command from client side to be used in server side.
Parameters
unparsed_ pointer to the unparsed string
query_params *qparams pointer to the struct where query parameters are stored
Returns
pointer to the parsed string
First predicate parsing ends here
Next predicates parsing start here
predicate parsing ends here
Next predicates parsing end here
Putting it together in a string
Definition at line 1238 of file utils.c.
References MAX_COLNAME_LEN, MAX_COLUMNS_PER_TABLE, and MAX_VALUE_LEN.
Referenced by handle_command().
int read_config (const char * config_file, struct config_params * params)
Read and load configuration parameters.
Parameters
config_file The name of the configuration file.
params The structure where config parameters are loaded.
Returns
Return 0 on success, -1 otherwise.
Open file for reading.
Process the config file.
Read a line from the file.
right size, proceed to process line
not the right size
Definition at line 1093 of file utils.c.
References config_params::concurrency, ERR_UNKNOWN, MAX_CONFIG_LINE_LEN, config_params::pass_, process_config_line(), config_params::server_host, config_params::server_port, and config_params::username.
Referenced by main().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
Returns
Return 0 on success, -1 otherwise.
Receive an entire line from a socket.
Parameters
sock Connection socket
buf String buffer
buflen Length of buffer
Returns
Return 0 on success, -1 otherwise. In order to avoid reading more than a line from the stream, this function only reads one byte at a time. This is very inefficient, and you are free to optimize it or implement your own function.
Return status.
Read one byte from scoket.
recv() was not successful, so stop.
Found end of line, so stop.
Keep going.
add null terminator in case it's not already there.
Definition at line 588 of file utils.c.
Referenced by main(), storage_auth(), storage_get(), storage_query(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
Keep sending the contents of the buffer until complete.
Returns
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
Parameters
sock Connection socket
buf String buffer
len Length of buffer
Returns
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
send() was not successful, so stop.
Definition at line 563 of file utils.c.
Referenced by handle_command(), storage_auth(), storage_get(), storage_query(), and storage_set().
char* set_parsing (char * unparsed_, struct set_params * sparams)
This is a function that parses the set command from client side to be used in server side.
Parameters
unparsed_ pointer to the unparsed string
set_params *sparams pointer to the struct where set parameters are stored
Returns
pointer to the parsed string
First predicate parsing ends here
Next predicates parsing start here
predicate parsing ends here
Next predicates parsing end here
Putting it together in a string
Definition at line 1540 of file utils.c.
References MAX_COLNAME_LEN, MAX_COLUMNS_PER_TABLE, and MAX_VALUE_LEN.
Referenced by handle_command().
Variable Documentation
FILE* file_ptr
added struct RecordElement to store key, data, and pointer to next RecordElement
Definition at line 30 of file client.c.